package org.cloudnovel.novel.core.support.error

enum class ErrorCode {
    NO_HANDLER_FOUND_ERROR,


    USER_NOT_FOUND_ERROR,
    PROFILE_NOT_FOUND_ERROR,
    PROFILED_MAX_COUNT_EXCEED,

    INTEREST_NOT_FOUND_ERROR,
    
    NOVEL_NOT_FOUND_ERROR,

    ALREADY_FOLLOWING_ERROR,
    NOT_FOLLOWING_PROFILE_ERROR,

    NOT_FOLLOWER_PROFILE_ERROR,
    SURVEY_NOT_FOUND_ERROR,
    ALREADY_JOINED_ERROR
}